// <auto-generated />
using System;
using Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516084102_AddNotificationLog")]
    partial class AddNotificationLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "severity", new[] { "safe", "warning", "danger" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AreaId"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area_name");

                    b.HasKey("AreaId");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("Core.Entities.History", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<float>("MaxWaterLevel")
                        .HasColumnType("real")
                        .HasColumnName("max_water_level");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Safe")
                        .HasColumnName("severity");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("HistoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("history", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Location", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlaceId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("PlaceId");

                    b.HasIndex("AreaId");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Core.Entities.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int?>("AssignedTechnicianTo")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_technician_to");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer")
                        .HasColumnName("priority_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("RequestId");

                    b.HasIndex("AssignedTechnicianTo");

                    b.HasIndex("PriorityId");

                    b.HasIndex("SensorId");

                    b.ToTable("maintenancerequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceRequests_Status", "\"status\" IN ('Pending','Assigned','InProgress','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Core.Entities.MaintenanceSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("AssignedTechnicianId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_technician_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("ScheduleMode")
                        .HasColumnType("text")
                        .HasColumnName("schedule_mode");

                    b.Property<string>("ScheduleType")
                        .HasColumnType("text")
                        .HasColumnName("schedule_type");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("ScheduleId");

                    b.HasIndex("AssignedTechnicianId");

                    b.HasIndex("SensorId");

                    b.ToTable("maintenanceschedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceSchedules_ScheduleMode", "\"schedule_mode\" IN ('Manual','Auto')");

                            t.HasCheckConstraint("CK_MaintenanceSchedules_ScheduleType", "\"schedule_type\" IN ('Weekly','Monthly','Quarterly')");

                            t.HasCheckConstraint("CK_MaintenanceSchedules_Status", "\"status\" IN ('Scheduled','Active','Paused','Completed','Overdue')");
                        });
                });

            modelBuilder.Entity("Core.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notification_type");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("integer")
                        .HasColumnName("technician_id");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId", "NotificationType")
                        .IsUnique();

                    b.ToTable("notificationlogs", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("priority_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriorityId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("PriorityId");

                    b.ToTable("priorities", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ForecastDataJson")
                        .HasColumnType("text")
                        .HasColumnName("forecast_data_json");

                    b.Property<string>("ForecastRiskLevel")
                        .HasColumnType("text")
                        .HasColumnName("forecast_risk_level");

                    b.HasKey("ReportId");

                    b.ToTable("report", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sensor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SensorId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<float?>("DangerThreshold")
                        .HasColumnType("real")
                        .HasColumnName("danger_threshold");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("installed_at");

                    b.Property<int?>("MaxLevel")
                        .HasColumnType("integer")
                        .HasColumnName("max_level");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<string>("SensorCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sensor_code");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sensor_name");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sensor_type");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specification");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("integer")
                        .HasColumnName("technician_id");

                    b.Property<float?>("WarningThreshold")
                        .HasColumnType("real")
                        .HasColumnName("warning_threshold");

                    b.HasKey("SensorId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("SensorCode")
                        .IsUnique();

                    b.HasIndex("TechnicianId");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("Core.Entities.SensorReading", b =>
                {
                    b.Property<long>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reading_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReadingId"));

                    b.Property<int>("BatteryPercent")
                        .HasColumnType("integer")
                        .HasColumnName("battery_percent");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_id");

                    b.Property<string>("SignalStrength")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signal_strength");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<float>("WaterLevelCm")
                        .HasColumnType("real")
                        .HasColumnName("water_level_cm");

                    b.HasKey("ReadingId");

                    b.HasIndex("SensorId");

                    b.ToTable("sensorreadings", (string)null);
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailOtpExpiredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("email_otp_expired_at");

                    b.Property<string>("EmailOtpHash")
                        .HasColumnType("text")
                        .HasColumnName("email_otp_hash");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Core.Entities.History", b =>
                {
                    b.HasOne("Core.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Core.Entities.Location", b =>
                {
                    b.HasOne("Core.Entities.Area", "Area")
                        .WithMany("Locations")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Core.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("Core.Entities.User", "AssignedTechnician")
                        .WithMany("MaintenanceRequestsAssigned")
                        .HasForeignKey("AssignedTechnicianTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_MaintenanceRequest_AssignedTechnician");

                    b.HasOne("Core.Entities.Priority", "Priority")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.Sensor", "Sensor")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTechnician");

                    b.Navigation("Priority");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Core.Entities.MaintenanceSchedule", b =>
                {
                    b.HasOne("Core.Entities.User", "AssignedTechnician")
                        .WithMany("MaintenanceSchedulesAssigned")
                        .HasForeignKey("AssignedTechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_MaintenanceSchedule_AssignedTechnician");

                    b.HasOne("Core.Entities.Sensor", "Sensor")
                        .WithMany("MaintenanceSchedules")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTechnician");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Core.Entities.Sensor", b =>
                {
                    b.HasOne("Core.Entities.Location", "Location")
                        .WithMany("Sensors")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "Technician")
                        .WithMany("SensorsMaintained")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Location");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Core.Entities.SensorReading", b =>
                {
                    b.HasOne("Core.Entities.Sensor", "Sensor")
                        .WithMany("SensorReadings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.HasOne("Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Core.Entities.Area", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Core.Entities.Location", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Core.Entities.Priority", b =>
                {
                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Entities.Sensor", b =>
                {
                    b.Navigation("MaintenanceRequests");

                    b.Navigation("MaintenanceSchedules");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("MaintenanceRequestsAssigned");

                    b.Navigation("MaintenanceSchedulesAssigned");

                    b.Navigation("SensorsMaintained");
                });
#pragma warning restore 612, 618
        }
    }
}
